spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/muses?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: nekoneko
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
